#!/usr/bin/env python3
"""
SecondSelf: The Cartographer (build_graph.py)
Reads wiki/ Markdown files and generates graph_data.js for the frontend.
"""

import os
import json
import re
from pathlib import Path

def parse_markdown_file(filepath: Path) -> dict:
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract Frontmatter
    frontmatter_match = re.search(r"^---\n(.*?)\n---", content, re.DOTALL)
    metadata = {}
    if frontmatter_match:
        lines = frontmatter_match.group(1).split("\n")
        for line in lines:
            if ":" in line:
                key, val = line.split(":", 1)
                key = key.strip()
                val = val.strip()
                # Basic handling for simple yaml (not full parser to avoid dependencies)
                if key != "tags" and not line.startswith("  -"):
                    metadata[key] = val

    # Attempt to extract summary
    summary_match = re.search(r"# Summary\n(.*?)\n---", content, re.DOTALL)
    summary = summary_match.group(1).strip() if summary_match else "No summary available."

    # Attempt to extract Semantic Links
    links = []
    link_section_match = re.search(r"## Related Notes\n(.*)", content, re.DOTALL)
    if link_section_match:
        link_lines = link_section_match.group(1).split("\n")
        for line in link_lines:
            match = re.search(r"\[\[(.*?)\]\]", line)
            if match:
                target = match.group(1).strip()
                links.append(target)

    # Label generation (first 4 words of summary)
    words = summary.split()
    label = " ".join(words[:4]) + "..." if len(words) > 4 else summary

    # PARA category
    category = metadata.get("category", "Resources")
    
    # ID is the filename
    node_id = filepath.name

    # Tooltip title (HTML allowed in vis.js tooltips if configured)
    tooltip_html = f"<b>{category}</b><br><br>{summary}"

    return {
        "id": node_id,
        "label": label,
        "group": category,
        "title": tooltip_html,
        "links": links
    }


def build_graph():
    script_dir = Path(__file__).resolve().parent
    wiki_dir = script_dir / "wiki"
    
    if not wiki_dir.exists():
        print(f"[ERROR] wiki/ directory not found at {wiki_dir}")
        return

    md_files = list(wiki_dir.glob("*.md"))
    
    nodes = []
    edges = []
    
    node_ids = set()

    # Build Nodes
    for filepath in md_files:
        data = parse_markdown_file(filepath)
        nodes.append({
            "id": data["id"],
            "label": data["label"],
            "group": data["group"],
            "title": data["title"],
            "shape": "dot",
            "size": 20
        })
        node_ids.add(data["id"])
        
    # Build Edges
    for filepath in md_files:
        data = parse_markdown_file(filepath)
        source_id = data["id"]
        for target_id in data["links"]:
            # Ensure the target actually exists to prevent broken edges
            if target_id in node_ids:
                edges.append({
                    "from": source_id,
                    "to": target_id,
                    "color": {"opacity": 0.4}
                })

    print(f"[INFO] Parsed {len(nodes)} nodes and {len(edges)} edges.")

    # Export to graph_data.js (avoids CORS issues on local file:// execution)
    output_js = script_dir / "graph_data.js"
    
    js_content = f"// Auto-generated by build_graph.py\n"
    js_content += f"const graphData = {{\n"
    js_content += f"  nodes: {json.dumps(nodes, indent=2)},\n"
    js_content += f"  edges: {json.dumps(edges, indent=2)}\n"
    js_content += f"}};\n"
    
    with open(output_js, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    print(f"[SUCCESS] Exported graph data to {output_js.name}")

if __name__ == "__main__":
    build_graph()
